### ISSUE TITLE
"endless zoom loop" in Chrome on Windows

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#132] opened 2023-10-06 11:33 UTC
Observed by @sherinsugathan, I believe in Chrome on Windows, but not seen by me:

> I see a zoom out animation playing in loop forever in my Windows Chrome browser for the address http://158.39.48.160/ml-webload.html

No clue what this might be.  The graph animates a bit when it is drawn but this sounds like something else.  @sherinsugathan, are you able to capture this somehow as a screenshot or video, or look in the developer console for errors while it's going on?

**Comment by lars-t-hansen** [comment] 2023-10-06 11:56
Possibly this: https://stackoverflow.com/questions/70376891/chartjs-in-endless-loop

**Comment by lars-t-hansen** [comment] 2023-10-06 13:14
I'm unable to repro this on any platform so far, including Chrome 117 on Windows 10.  It's clear that chart.js changes its animation behavior depending on the window size: at small sizes, it does not animate; at intermediate sizes, it does, and then at very large (or sufficently full-screen-like) sizes it does not, again.

Since this is hard to repro I'm going to remove the Important label, but we'll keep the bug open until something actionable happens.

**Comment by sherinsugathan** [comment] 2023-10-06 14:06
Yes, I do see different behavior for different windows sizes. I am adding some more observations below:
- I have same issue in Microsoft Edge browser.
- At maximized and 125% scale state and some specific zoom levels, there is no animation at all. This behavior is common in all browsers that I have.
- At the windows level "scale and layout", I am using a recommended scale of 250%.
- There are open issues with the library itself (https://github.com/chartjs/Chart.js/issues/11089) somewhat close to the scenario I see. So I would not recommend spending too much time on this right now.

**Comment by ashenr** [comment] 2024-08-21 12:25
With the new dashboard we are now using Recharts library for charts.
Since the original issue was caused by ChartsJS, I think it's safe to close this issue.

**Closed by ashenr** 2024-08-21 12:25 UTC
Labels: task:bug, pri:low, task:ux, component:dashboard
